workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: 1. Create Android platform structure
        script: flutter create . --platforms=android
      - name: 2. Fetch packages manually
        script: flutter pub get
      - name: 3. Build Release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
