workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Generate clean Flutter platforms
        script: flutter create . --platforms=android
      - name: Get dependencies
        script: flutter pub get
      - name: Build Release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
