workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Initialize Android Platform
        script: |
          flutter create . --platforms=android
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
